import { writeFileSync, mkdirSync, existsSync, readdirSync, rmSync } from 'fs';
import { join } from 'path';
import type { LibraryDatabase, DbPlaylist, DbTrack } from '../state/library.js';

/**
 * Generates human-readable Markdown files from the SQLite database.
 * These files are tracked by Git to provide meaningful diffs.
 */
export class MarkdownGenerator {
  private workspacePath: string;
  private playlistsDir: string;

  constructor(workspacePath: string) {
    this.workspacePath = workspacePath;
    this.playlistsDir = join(workspacePath, 'Playlists');
  }

  /**
   * Generate all markdown files from the database
   */
  generateAll(library: LibraryDatabase): void {
    // Ensure Playlists directory exists
    mkdirSync(this.playlistsDir, { recursive: true });

    // Get all playlists from database
    const playlists = library.getAllPlaylists();

    // Track which files we generate (to clean up orphans)
    const generatedFiles = new Set<string>();

    // Generate a markdown file for each playlist
    for (const playlist of playlists) {
      const tracks = library.getPlaylistTracks(playlist.id);
      const filename = this.generatePlaylistMarkdown(playlist, tracks);
      generatedFiles.add(filename);
    }

    // Generate library overview
    this.generateLibraryOverview(library, playlists);
    generatedFiles.add('_library.md');

    // Clean up orphaned markdown files
    this.cleanupOrphans(generatedFiles);
  }

  /**
   * Generate markdown for a single playlist
   */
  private generatePlaylistMarkdown(
    playlist: DbPlaylist,
    tracks: Array<DbTrack & { position: number; added_at: string | null }>
  ): string {
    const safeName = this.sanitizeFilename(playlist.name);
    const filename = `${safeName}.md`;
    const filepath = join(this.playlistsDir, filename);

    const totalDuration = tracks.reduce((sum, t) => sum + (t.duration_ms || 0), 0);
    const durationStr = this.formatDuration(totalDuration);

    let content = `# ${playlist.name}\n\n`;
    content += `> ${tracks.length} tracks • ${durationStr} total`;

    if (playlist.description) {
      content += `\n>\n> ${playlist.description}`;
    }

    content += `\n\n`;
    content += `<!-- playlist_id: ${playlist.id} -->\n`;
    content += `<!-- snapshot_id: ${playlist.snapshot_id || 'local'} -->\n`;
    content += `<!-- last_synced: ${playlist.last_synced_at || 'never'} -->\n\n`;

    if (tracks.length === 0) {
      content += `*No tracks in this playlist*\n`;
    } else {
      // Table header
      content += `| # | Track | Artist | Album | Duration |\n`;
      content += `|--:|-------|--------|-------|----------|\n`;

      // Table rows
      for (const track of tracks) {
        const artists = this.parseArtists(track.artists);
        const duration = this.formatTrackDuration(track.duration_ms);
        const trackName = this.escapeMarkdown(track.name);
        const artistStr = this.escapeMarkdown(artists.join(', '));
        const albumStr = this.escapeMarkdown(track.album || '');

        content += `| ${track.position} | ${trackName} | ${artistStr} | ${albumStr} | ${duration} |\n`;
      }
    }

    content += `\n<!-- track_ids: ${tracks.map(t => t.id).join(',')} -->\n`;

    writeFileSync(filepath, content);
    return filename;
  }

  /**
   * Generate library overview markdown
   */
  private generateLibraryOverview(library: LibraryDatabase, playlists: DbPlaylist[]): void {
    const filepath = join(this.playlistsDir, '_library.md');
    const stats = library.getStats();

    let content = `# 🎵 Spotify Library\n\n`;
    content += `> ${stats.playlists} playlists • ${stats.tracks} unique tracks\n\n`;

    content += `## Playlists\n\n`;
    content += `| Playlist | Tracks | Last Synced |\n`;
    content += `|----------|-------:|-------------|\n`;

    for (const playlist of playlists) {
      const name = this.escapeMarkdown(playlist.name);
      const synced = playlist.last_synced_at
        ? new Date(playlist.last_synced_at).toLocaleDateString()
        : 'Never';
      content += `| [${name}](./${this.sanitizeFilename(playlist.name)}.md) | ${playlist.track_count} | ${synced} |\n`;
    }

    content += `\n---\n`;
    content += `*Generated by SpotifyFS*\n`;

    writeFileSync(filepath, content);
  }

  /**
   * Remove markdown files that no longer correspond to playlists
   */
  private cleanupOrphans(generatedFiles: Set<string>): void {
    if (!existsSync(this.playlistsDir)) return;

    const files = readdirSync(this.playlistsDir);
    for (const file of files) {
      if (file.endsWith('.md') && !generatedFiles.has(file)) {
        rmSync(join(this.playlistsDir, file));
      }
    }
  }

  /**
   * Generate markdown for a single playlist (for incremental updates)
   */
  updatePlaylist(library: LibraryDatabase, playlistId: string): void {
    const playlist = library.getPlaylist(playlistId);
    if (!playlist) return;

    const tracks = library.getPlaylistTracks(playlistId);
    this.generatePlaylistMarkdown(playlist, tracks);
  }

  /**
   * Remove markdown for a deleted playlist
   */
  removePlaylist(playlistName: string): void {
    const safeName = this.sanitizeFilename(playlistName);
    const filepath = join(this.playlistsDir, `${safeName}.md`);
    if (existsSync(filepath)) {
      rmSync(filepath);
    }
  }

  // ==================== Helpers ====================

  private sanitizeFilename(name: string): string {
    return name
      .replace(/[<>:"/\\|?*]/g, '')
      .replace(/\s+/g, ' ')
      .trim()
      .substring(0, 100);
  }

  private escapeMarkdown(text: string): string {
    return text.replace(/\|/g, '\\|').replace(/\n/g, ' ');
  }

  private parseArtists(artistsJson: string): string[] {
    try {
      return JSON.parse(artistsJson);
    } catch {
      return [artistsJson];
    }
  }

  private formatDuration(ms: number): string {
    const totalSeconds = Math.floor(ms / 1000);
    const hours = Math.floor(totalSeconds / 3600);
    const minutes = Math.floor((totalSeconds % 3600) / 60);

    if (hours > 0) {
      return `${hours}h ${minutes}m`;
    }
    return `${minutes} min`;
  }

  private formatTrackDuration(ms: number): string {
    const totalSeconds = Math.floor(ms / 1000);
    const minutes = Math.floor(totalSeconds / 60);
    const seconds = totalSeconds % 60;
    return `${minutes}:${seconds.toString().padStart(2, '0')}`;
  }
}
